# Generated by Django 3.2.2 on 2021-06-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Professor', models.CharField(default='', max_length=255)),
                ('IC', models.CharField(default='', max_length=255)),
                ('remunerada', models.BooleanField(default=False)),
                ('data_encerramento', models.CharField(default='', max_length=10)),
                ('requisitos', models.BooleanField(default=False)),
                ('assunto', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
